# config/default.yaml
sockets:
  up:
    host: "0.0.0.0"
    port: 4225
    base_path: "/command"
    handshake_timeout: 3000
    heartbeat_interval: 15000
  down:
    host: "0.0.0.0"
    port: 4226
    cache_ttl: 1000

entity:
  update:
    batch_interval: 100